# Generated by Django 5.2.17 on 2026-09-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('text', models.TextField(blank=True, verbose_name='texto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('DONE', 'Hecha')], default='PENDING', max_length=20, verbose_name='estado')),
                ('pos_x', models.IntegerField(default=0, verbose_name='posición X')),
                ('pos_y', models.IntegerField(default=0, verbose_name='posición Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['created_at'],
            },
        ),
    ]
